---
- name: Deploy Alertmanager config
  template:
    src: alertmanager.yml.j2
    dest: "{{ alertmanager_install_dir }}/alertmanager.yml"
    owner: alertmanager
    group: alertmanager
  notify: restart alertmanager
