---
- name: Create alertmanager user
  user:
    name: alertmanager
    system: true
    shell: /bin/false

- name: Create Alertmanager directories
  file:
    path: "{{ item }}"
    state: directory
    owner: alertmanager
    group: alertmanager
    mode: '0755'
  loop:
    - "{{ alertmanager_install_dir }}"
    - "{{ alertmanager_install_dir }}/data"

- name: Download Alertmanager
  get_url:
    url: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
    dest: /tmp/alertmanager.tar.gz

- name: Extract Alertmanager
  unarchive:
    src: /tmp/alertmanager.tar.gz
    dest: "{{ alertmanager_install_dir }}"
    remote_src: true
    extra_opts: [--strip-components=1]
    creates: "{{ alertmanager_install_dir }}/alertmanager"

- name: Fix ownership
  file:
    path: "{{ alertmanager_install_dir }}"
    owner: alertmanager
    group: alertmanager
    recurse: true
