---
- name: Initialize K8s control plane
  command: >
    kubeadm init
    --control-plane-endpoint "{{ k8s_api_vip }}:6443"
    --upload-certs
    --pod-network-cidr "{{ k8s_pod_network_cidr }}"
  args:
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_init_output

- name: Create .kube directory for root
  file:
    path: /root/.kube
    state: directory
    mode: '0755'

- name: Copy kubeconfig for root
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: true
    owner: root
    group: root
    mode: '0600'
