---
- name: Read master join command from bastion
  delegate_to: localhost
  slurp:
    src: /tmp/k8s_master_join_command.sh
  register: master_join_cmd

- name: Join additional master nodes to control plane
  command: "{{ master_join_cmd.content | b64decode | trim }}"
  args:
    creates: /etc/kubernetes/admin.conf

- name: Create .kube directory
  file:
    path: /root/.kube
    state: directory
    mode: '0755'

- name: Copy kubeconfig
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: true
    mode: '0600'
