---
- name: Download OTel Collector binary
  get_url:
    url: "https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v{{ otelcol_version }}/otelcol-contrib_{{ otelcol_version }}_linux_amd64.tar.gz"
    dest: /tmp/otelcol.tar.gz

- name: Create OTel Collector install dir
  file:
    path: "{{ otelcol_install_dir }}"
    state: directory
    mode: '0755'

- name: Extract OTel Collector
  unarchive:
    src: /tmp/otelcol.tar.gz
    dest: "{{ otelcol_install_dir }}"
    remote_src: true
    creates: "{{ otelcol_install_dir }}/otelcol-contrib"
