# Overlay PROD — apply lên K8s Prod cluster (10.20.x.x VPC)
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: techshop

resources:
  - ../../base
  - app-secrets.yaml      # giá trị thật, KHÔNG commit (xem .gitignore)
  - patches/bff-user-hpa.yaml   # HPA mới (không có trong base) — add làm resource
  - patches/bff-admin-hpa.yaml

commonAnnotations:
  techshop.io/env: prod

images:
  - name: ghcr.io/pham-van-khiem-toan-tin/discovery-service
    newName: asia-southeast1-docker.pkg.dev/gcp-apse1-prj-sh-access-003/techshop/discovery-service
    newTag: prod
  - name: ghcr.io/pham-van-khiem-toan-tin/identity-service
    newName: asia-southeast1-docker.pkg.dev/gcp-apse1-prj-sh-access-003/techshop/identity-service
    newTag: prod
  - name: ghcr.io/pham-van-khiem-toan-tin/catalog-service
    newName: asia-southeast1-docker.pkg.dev/gcp-apse1-prj-sh-access-003/techshop/catalog-service
    newTag: prod
  - name: ghcr.io/pham-van-khiem-toan-tin/order-service
    newName: asia-southeast1-docker.pkg.dev/gcp-apse1-prj-sh-access-003/techshop/order-service
    newTag: prod
  - name: ghcr.io/pham-van-khiem-toan-tin/inventory-service
    newName: asia-southeast1-docker.pkg.dev/gcp-apse1-prj-sh-access-003/techshop/inventory-service
    newTag: prod
  - name: ghcr.io/pham-van-khiem-toan-tin/payment-service
    newName: asia-southeast1-docker.pkg.dev/gcp-apse1-prj-sh-access-003/techshop/payment-service
    newTag: prod
  - name: ghcr.io/pham-van-khiem-toan-tin/search-service
    newName: asia-southeast1-docker.pkg.dev/gcp-apse1-prj-sh-access-003/techshop/search-service
    newTag: prod
  - name: ghcr.io/pham-van-khiem-toan-tin/bff-user
    newName: asia-southeast1-docker.pkg.dev/gcp-apse1-prj-sh-access-003/techshop/bff-user
    newTag: prod
  - name: ghcr.io/pham-van-khiem-toan-tin/bff-admin
    newName: asia-southeast1-docker.pkg.dev/gcp-apse1-prj-sh-access-003/techshop/bff-admin
    newTag: prod

# Prod: scale replicas — service quan trọng = 2, còn lại = 1
replicas:
  - name: identity-service
    count: 2
  - name: catalog-service
    count: 2
  - name: order-service
    count: 2
  - name: inventory-service
    count: 1
  - name: payment-service
    count: 2
  - name: search-service
    count: 1
  - name: bff-user
    count: 2
  - name: bff-admin
    count: 1

patches:
  - path: patches/ingress-hosts.yaml
  - path: patches/bff-user-redirect.yaml
  - path: patches/bff-admin-redirect.yaml
  - target:
      kind: ConfigMap
      name: app-config
    patch: |-
      - op: replace
        path: /data/SPRING_PROFILES_ACTIVE
        value: "k8s,prod"
      - op: add
        path: /data/LOGGING_LEVEL_ROOT
        value: "WARN"
