---
- name: Create prometheus user
  user:
    name: prometheus
    system: true
    shell: /bin/false

- name: Create Prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - "{{ prometheus_install_dir }}"
    - "{{ prometheus_data_dir }}"

- name: Download Prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: "{{ prometheus_install_dir }}"
    remote_src: true
    extra_opts: [--strip-components=1]
    creates: "{{ prometheus_install_dir }}/prometheus"

- name: Fix ownership
  file:
    path: "{{ prometheus_install_dir }}"
    owner: prometheus
    group: prometheus
    recurse: true
