---
- name: Deploy Prometheus systemd service
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify: restart prometheus

- name: Enable and start Prometheus
  systemd:
    name: prometheus
    enabled: true
    state: started
    daemon_reload: true
