---
- name: Enable and start Grafana
  systemd:
    name: grafana-server
    enabled: true
    state: started
    daemon_reload: true

- name: Wait for Grafana to be ready
  wait_for:
    port: "{{ grafana_port }}"
    delay: 5
    timeout: 60
