# Override Ingress hosts cho môi trường prod
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: techshop-ingress
  namespace: techshop
  annotations:
    # Cho phép FE (www / cms) gọi BFF (shop / admin) kèm cookie
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://www.techshop.local, http://cms.techshop.local"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, PATCH, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type, Authorization, X-Requested-With, X-CSRF-TOKEN"
spec:
  rules:
    - host: shop.techshop.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bff-user
                port:
                  number: 8081
    - host: admin.techshop.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bff-admin
                port:
                  number: 8088
    - host: identity.techshop.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: identity-service
                port:
                  number: 8085
    - host: www.techshop.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ecommerce-customer
                port:
                  number: 80
    - host: cms.techshop.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: techshop-admin
                port:
                  number: 80
