# Override Ingress hosts cho môi trường prod
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: techshop-ingress
  namespace: techshop
spec:
  rules:
    - host: shop.techshop.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bff-user
                port:
                  number: 8081
    - host: admin.techshop.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bff-admin
                port:
                  number: 8088
    - host: identity.techshop.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: identity-service
                port:
                  number: 8085
