# Override redirect URI cho OAuth2 client của BFF (dev)
apiVersion: apps/v1
kind: Deployment
metadata: { name: bff-user, namespace: techshop }
spec:
  template:
    spec:
      containers:
        - name: bff-user
          env:
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_USER_IDP_REDIRECT_URI
              value: "http://shop.dev.techshop.local/login/oauth2/code/user-idp"
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: bff-admin, namespace: techshop }
spec:
  template:
    spec:
      containers:
        - name: bff-admin
          env:
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_ADMIN_IDP_REDIRECT_URI
              value: "http://admin.dev.techshop.local/login/oauth2/code/admin-idp"
