# Override redirect URI cho bff-admin (dev)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-admin
  namespace: techshop
spec:
  template:
    spec:
      containers:
        - name: bff-admin
          env:
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_ADMIN_IDP_REDIRECT_URI
              value: "http://admin.dev.sontx.online/login/oauth2/code/admin-idp"
            # OIDC discovery phải đi qua public URL để authorization_endpoint
            # trong discovery doc là public (browser redirect được).
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_MY_IDENTITY_PROVIDER_ISSUER_URI
              value: "http://identity.dev.sontx.online"
