# Dev: chạy 1 replica cho tất cả service (tiết kiệm tài nguyên)
apiVersion: apps/v1
kind: Deployment
metadata: { name: identity-service, namespace: techshop }
spec: { replicas: 1 }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: catalog-service, namespace: techshop }
spec: { replicas: 1 }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: order-service, namespace: techshop }
spec: { replicas: 1 }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: inventory-service, namespace: techshop }
spec: { replicas: 1 }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: payment-service, namespace: techshop }
spec: { replicas: 1 }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: search-service, namespace: techshop }
spec: { replicas: 1 }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: bff-user, namespace: techshop }
spec: { replicas: 1 }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: bff-admin, namespace: techshop }
spec: { replicas: 1 }
