---
# Install kubeadm, kubelet, kubectl
- name: Add Kubernetes GPG key
  apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
    state: present

- name: Add Kubernetes repository
  apt_repository:
    repo: "deb https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
    state: present

- name: Install kubeadm, kubelet, kubectl
  apt:
    name:
      - kubeadm=1.29.*
      - kubelet=1.29.*
      - kubectl=1.29.*
    state: present
    update_cache: true

- name: Hold kubeadm, kubelet, kubectl at current version
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubeadm
    - kubelet
    - kubectl

- name: Enable and start kubelet
  systemd:
    name: kubelet
    enabled: true
    state: started
